export const ROBOTS_LIST = "ROBOTS_LIST";
export const LOAD_ROBOTS = "LOAD_ROBOTS";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REDUCE_ROBOT_STOCK = "REDUCE_ROBOT_STOCK";
export const UPDATE_STOCK_COUNT = "UPDATE_STOCK_COUNT";
